# Generated by Django 5.0.7 on 2024-09-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_anesthesiologist_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaAnestesiologista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início do Turno')),
                ('data_fim', models.DateTimeField(verbose_name='Fim do Turno')),
                ('coringa', models.BooleanField(default=False, verbose_name='Coringa')),
                ('fixo', models.BooleanField(default=False, verbose_name='Fixo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('anestesiologista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.anesthesiologist', verbose_name='Anestesiologista')),
            ],
            options={
                'verbose_name': 'Escala do Anestesiologista',
                'verbose_name_plural': 'Escalas dos Anestesiologistas',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255, verbose_name='Nome do Paciente')),
                ('procedimento', models.CharField(max_length=255, verbose_name='Procedimento')),
                ('data_horario', models.DateTimeField(verbose_name='Data e Horário Marcados')),
                ('visita_pre_anestesica', models.BooleanField(default=False, verbose_name='Visita Pré-Anestésica Realizada')),
                ('foto_anexo', models.ImageField(blank=True, null=True, upload_to='anexos/', verbose_name='Anexo de Foto')),
                ('nome_responsavel_visita', models.CharField(blank=True, max_length=255, verbose_name='Nome do Responsável pela Visita')),
                ('data_visita_pre_anestesica', models.DateField(blank=True, null=True, verbose_name='Data da Visita Pré-Anestésica')),
                ('link_nps', models.URLField(blank=True, verbose_name='Link de Pesquisa de Satisfação')),
                ('anestesista_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.anesthesiologist', verbose_name='Anestesista Responsável')),
                ('cirurgiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.surgeon', verbose_name='Cirurgião')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.hospitalclinic', verbose_name='Hospital/Clínica')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
    ]
