# Generated by Django 5.0.7 on 2024-09-04 17:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_escalaanestesiologista_group_procedimento_group'),
        ('registration', '0004_anesthesiologist_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='contato_pacinete',
            field=models.CharField(default='', max_length=255, verbose_name='Contato do Paciente'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='outro_local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Outro Local'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='procedimento_type',
            field=models.CharField(choices=[('cirurgia_procedimento', 'Cirurgia'), ('fora_centro_procedimento', 'Procedimento Fora do Centro Cirúrgico'), ('exame_procedimento', 'Exame')], default='cirurgia_procedimento', max_length=40, verbose_name='Tipo de Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Horário Marcados'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='foto_anexo',
            field=models.ImageField(blank=True, null=True, upload_to='anexos/', verbose_name='Anexo Visita Pré-Anestésica'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.hospitalclinic', verbose_name='Hospital/Clínica'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='link_nps',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Pesquisa de Satisfação'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome_paciente',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do Paciente'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome_responsavel_visita',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Responsável pela Visita'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='procedimento',
            field=models.CharField(default='', max_length=255, verbose_name='Procedimento'),
        ),
    ]
