# Generated by Django 5.0.7 on 2024-09-04 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_procedimento_contato_pacinete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Horário de Término'),
        ),
    ]
