# Generated by Django 5.0.7 on 2024-09-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_procedimento_contato_pacinete_and_more'),
        ('registration', '0004_anesthesiologist_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='cirurgiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.surgeon', verbose_name='Cirurgião'),
        ),
    ]
