# Generated by Django 5.0.7 on 2024-09-11 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_alter_escalaanestesiologista_dias_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='dias_da_semana',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], max_length=1), blank=True, default=list, size=None, verbose_name='Dias da Semana'),
        ),
    ]
