# Generated by Django 5.0.7 on 2024-09-14 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalaanestesiologista',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='escalaanestesiologista',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='escalaanestesiologista',
            name='dias_da_semana',
        ),
        migrations.AddField(
            model_name='escalaanestesiologista',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Escala'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
