# Generated by Django 5.0.7 on 2024-09-26 21:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_alter_procedimento_data_horario_fim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='link_nps',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='clareza_informacoes',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Clareza das informações'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='comentario_adicional',
            field=models.TextField(blank=True, null=True, verbose_name='Comentário adicional'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='comunicacao_disponibilidade',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Comunicação e disponibilidade'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='conforto_seguranca',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Conforto e segurança'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='csat_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CSAT Score'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='nps_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='satisfacao_geral',
            field=models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Satisfação geral'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='survey_response',
            field=models.TextField(blank=True, null=True, verbose_name='Survey Response'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2024, 9, 26, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 9, 26, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
    ]
