# Generated by Django 5.0.7 on 2024-09-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_remove_procedimento_link_nps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='survey_response',
        ),
    ]
