# Generated by Django 5.0.7 on 2024-10-03 20:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_alter_escalaanestesiologista_hora_fim_and_more'),
        ('registration', '0005_groups_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2024, 10, 3, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 10, 3, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='anestesista_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.anesthesiologist', verbose_name='Anestesista Responsável'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
    ]
