# Generated by Django 5.0.7 on 2024-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='convenio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Convênio'),
        ),
    ]
