# Generated by Django 5.0.7 on 2024-10-16 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0023_procedimento_convenio'),
        ('registration', '0005_groups_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='anestesista_responsavel',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='anestesistas_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='procedimentos', to='registration.anesthesiologist', verbose_name='Anestesistas Responsáveis'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2024, 10, 16, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 10, 16, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='cpf_paciente',
            field=models.CharField(blank=True, default='000.000.000-00', max_length=15, null=True, verbose_name='CPF do Paciente'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 16, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
    ]
