# Generated by Django 5.0.7 on 2024-10-28 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0026_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='adesao_checklist',
            field=models.BooleanField(blank=True, null=True, verbose_name='Adesão ao check list de segurança'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='adesao_profilaxia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Adesão aos protocolos de profilaxia antibiótica e de prevenção de TVP/TEP'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='conformidade_diretrizes',
            field=models.BooleanField(blank=True, null=True, verbose_name='Conformidade com diretrizes e protocolos'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='data_horario_fim_efetivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Término Efetivo'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='data_horario_inicio_efetivo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Início Efetivo'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='encaminhamento_uti',
            field=models.BooleanField(blank=True, null=True, verbose_name='Encaminhamentos não programado à UTI'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='evento_adverso_evitavel',
            field=models.BooleanField(blank=True, null=True, verbose_name='Evento adverso evitável'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='eventos_adversos_graves',
            field=models.BooleanField(blank=True, null=True, verbose_name='Eventos adversos graves (broncoaspiração, PCR, etc)'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='eventos_adversos_graves_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição dos eventos adversos graves'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='ponv',
            field=models.BooleanField(blank=True, null=True, verbose_name='PONV'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='reacao_alergica_grave',
            field=models.BooleanField(blank=True, null=True, verbose_name='Reação alérgica grave'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='reacao_alergica_grave_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da reação alérgica grave'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tipo_cobranca',
            field=models.CharField(blank=True, choices=[('cooperativa', 'Cooperativa'), ('hospital', 'Hospital'), ('particular', 'Particular')], max_length=20, null=True, verbose_name='Cobrança via'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='uso_tecnicas_assepticas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uso adequado de técnicas assépticas'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='valor_cobranca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor (se hospital e particular) / número da guia (se coop)'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2024, 10, 28, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 10, 28, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
    ]
