# Generated by Django 5.0.7 on 2024-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0028_procedimento_dor_pos_operatoria_imediata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='dor_pos_operatoria_imediata',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dor pós operatória imediata'),
        ),
    ]
