# Generated by Django 5.0.7 on 2024-10-30 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0029_alter_procedimento_dor_pos_operatoria_imediata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='dor_pos_operatoria_imediata',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='adaptacao_ventilador',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adaptação ao ventilador mecânico'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='atividade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='choro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Choro'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='consolabilidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consolabilidade'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='consolabilidade_painad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consolabilidade'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='dor_pos_operatoria',
            field=models.BooleanField(default=False, verbose_name='Dor pós operatória imediata'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='escala',
            field=models.CharField(choices=[('EVA', '<span class="scale-name">EVA</span> &nbsp; &nbsp; &nbsp;Adultos e crianças maiores que 7 anos.'), ('FLACC', '<span class="scale-name">FLACC</span> &nbsp; &nbsp; &nbsp;Crianças menores que 7 anos ou pacientes não verbais.'), ('BPS', '<span class="scale-name">BPS</span> &nbsp; &nbsp; &nbsp;Pacientes intubados e sedados.'), ('PAINAD-B', '<span class="scale-name">PAINAD-B</span> &nbsp; &nbsp; &nbsp;Pacientes com demência avançada.')], default='EVA', max_length=10, verbose_name='Qual escala?'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='eva_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quanto?'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='expressao_facial',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expressão facial'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='expressao_facial_painad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expressão facial'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='face',
            field=models.IntegerField(blank=True, null=True, verbose_name='Face'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='linguagem_corporal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Linguagem corporal'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='movimentos_membros_superiores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Movimentos dos membros superiores'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='pernas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pernas'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='respiracao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Respiração'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='vocalizacao_negativa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vocalização negativa'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2024, 10, 30, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 10, 30, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='cpf_paciente',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CPF do Paciente'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
    ]
