# Generated by Django 5.0.7 on 2024-10-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0030_remove_procedimento_dor_pos_operatoria_imediata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='escala',
            field=models.CharField(blank=True, choices=[('EVA', '<span class="scale-name">EVA</span> &nbsp; &nbsp; &nbsp;Adultos e crianças maiores que 7 anos.'), ('FLACC', '<span class="scale-name">FLACC</span> &nbsp; &nbsp; &nbsp;Crianças menores que 7 anos ou pacientes não verbais.'), ('BPS', '<span class="scale-name">BPS</span> &nbsp; &nbsp; &nbsp;Pacientes intubados e sedados.'), ('PAINAD-B', '<span class="scale-name">PAINAD-B</span> &nbsp; &nbsp; &nbsp;Pacientes com demência avançada.')], max_length=10, null=True, verbose_name='Qual escala?'),
        ),
    ]
