# Generated by Django 5.0.7 on 2024-10-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0031_alter_procedimento_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='dor_pos_operatoria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Dor pós operatória imediata'),
        ),
    ]
