# Generated by Django 5.0.7 on 2024-10-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0032_alter_procedimento_dor_pos_operatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='procedimento',
            field=models.CharField(default='', max_length=255, verbose_name='Procedimento Principal'),
        ),
    ]
