# Generated by Django 5.0.7 on 2024-10-31 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0034_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='procedimento',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='procedimento_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.procedimentodetalhes', verbose_name='Procedimento Principal'),
        ),
    ]
