# Generated by Django 5.0.7 on 2024-11-05 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0036_alter_procedimentodetalhes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2024, 11, 5, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2024, 11, 5, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='eventos_adversos_graves_desc',
            field=models.CharField(blank=True, choices=[('broncoaspiracao', 'Broncoaspiração'), ('pcr', 'Parada Cardiorrespiratória (PCR)'), ('hemorragia', 'Hemorragia Maciça'), ('embolia', 'Embolia Pulmonar'), ('choque_anafilatico', 'Choque Anafilático'), ('lesao_orgao', 'Lesão de Órgão Não-Alvo'), ('iam', 'Infarto Agudo do Miocárdio'), ('avc', 'Acidente Vascular Cerebral (AVC)'), ('sirs', 'Síndrome da Resposta Inflamatória Sistêmica (SIRS)'), ('tvp', 'Trombose Venosa Profunda (TVP)'), ('ira', 'Insuficiência Renal Aguda'), ('pneumotorax', 'Pneumotórax'), ('sind_compartimental', 'Síndrome Compartimental'), ('hipertermia', 'Hipertermia Maligna'), ('deiscencia', 'Deiscência de Sutura'), ('lesao_nervo', 'Lesão de Nervo Periférico'), ('cegueira', 'Cegueira Pós-Operatória'), ('sdra', 'Síndrome do Desconforto Respiratório Agudo (SDRA)'), ('reacao_transfusional', 'Reação Transfusional Hemolítica Aguda'), ('sepse', 'Sepse Pós-Operatória')], max_length=50, null=True, verbose_name='Descrição do evento adverso grave'),
        ),
    ]
