# Generated by Django 5.0.7 on 2024-11-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0037_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='tipo_pagamento_direto',
            field=models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Tipo de pagamento direto'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tipo_cobranca',
            field=models.CharField(blank=True, choices=[('cooperativa', 'Cooperativa'), ('hospital', 'Hospital'), ('particular', 'Direta')], max_length=20, null=True, verbose_name='Cobrança via'),
        ),
    ]
