# Generated by Django 5.0.7 on 2025-02-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0047_convenios_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimento',
            name='convenio',
        ),
    ]
