# Generated by Django 5.0.7 on 2025-02-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0048_remove_procedimento_convenio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='convenio_new',
            new_name='convenio',
        ),
    ]
