# Generated by Django 5.0.7 on 2025-03-06 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0049_rename_convenio_new_procedimento_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='cirurgiao_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cirurgião (Se não cadastrado)'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2025, 3, 6, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 3, 6, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='data_horario_fim',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 20, 0, tzinfo=datetime.timezone.utc), verbose_name='Previsão de Término'),
        ),
    ]
