# Generated by Django 5.0.7 on 2025-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0057_procedimentodetalhes_codigo_procedimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentodetalhes',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
