# Generated by Django 5.0.7 on 2025-06-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0062_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='procedimento_type',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('cirurgia_procedimento_ambulatorial', 'Cirurgia / Procedimento ambulatorial')], default='cirurgia_procedimento_ambulatorial', max_length=40, verbose_name='Tipo de Procedimento'),
        ),
    ]
