# Generated by Django 5.0.7 on 2025-06-28 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0063_alter_procedimento_procedimento_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimento",
            name="tipo_procedimento",
            field=models.CharField(
                blank=True,
                choices=[("urgencia", "Urgência"), ("eletiva", "Eletiva")],
                default="eletiva",
                max_length=10,
                null=True,
                verbose_name="Tipo de Procedimento (Agenda)",
            ),
        ),
        migrations.AlterField(
            model_name="escalaanestesiologista",
            name="hora_fim",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 6, 28, 17, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Hora de Fim do Turno",
            ),
        ),
        migrations.AlterField(
            model_name="escalaanestesiologista",
            name="hora_inicio",
            field=models.TimeField(
                default=datetime.datetime(
                    2025, 6, 28, 8, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Hora de Início do Turno",
            ),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="data_horario_fim",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 28, 20, 0, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Previsão de Término",
            ),
        ),
    ]
