# Generated by Django 5.0.7 on 2025-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0064_procedimento_tipo_procedimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='tipo_procedimento',
            field=models.CharField(blank=True, choices=[('urgencia', 'Urgência'), ('eletiva', 'Eletiva')], default='eletiva', max_length=10, null=True, verbose_name='Eletiva ou Urgência'),
        ),
    ]
