# Generated by Django 5.0.7 on 2025-09-29 17:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0068_procedimento_tipo_clinica_and_more'),
        ('registration', '0017_remove_customuser_user_type_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='anestesistas_livres',
            field=models.TextField(blank=True, default='', verbose_name='Anestesistas (livre)'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='cooperado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_como_cooperado', to='registration.anesthesiologist', verbose_name='Cooperado'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2025, 9, 29, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 9, 29, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
    ]
