# Generated by Django 5.0.7 on 2025-10-14 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0070_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2025, 10, 14, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 10, 14, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='tipo_clinica',
            field=models.CharField(blank=True, choices=[('aparelho_digestivo', 'Aparelho Digestivo'), ('cabeca_pescoco', 'Cabeça e Pescoço'), ('cardiovascular', 'Cardiovascular'), ('coloproctologia', 'Coloproctologia'), ('cranio_maxilo_facial', 'Crânio-Maxilo-Facial'), ('dermatologia', 'Dermatologia'), ('geral', 'Geral'), ('ginecologia', 'Ginecologia'), ('neurocirurgia', 'Neurocirurgia'), ('mastologia', 'Mastologia'), ('obstetricia', 'Obstetrícia'), ('oftalmologia', 'Oftalmologia'), ('oncologica', 'Oncológica'), ('ortopedia_traumatologia', 'Ortopedia e Traumatologia'), ('otorrinolaringologia', 'Otorrinolaringologia'), ('pediatrica', 'Pediátrica'), ('plastica', 'Plástica'), ('cirurgia_toracica_obstetricia', 'Cirurgia Torácica Obstetrícia'), ('broncoscopia', 'Broncoscopia'), ('hemodinamica', 'Hemodinâmica'), ('radiologia', 'Radiologia'), ('toracica', 'Torácica'), ('trauma', 'Trauma'), ('urologia', 'Urologia'), ('vascular', 'Vascular')], max_length=50, null=True, verbose_name='Clínica (Perfil Cirúrgico)'),
        ),
    ]
