# Generated by Django 5.0.7 on 2025-12-18 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0072_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='acomodacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acomodação'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2025, 12, 18, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 12, 18, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
    ]
