# Generated by Django 5.0.7 on 2025-12-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0074_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='acomodacao',
            field=models.CharField(blank=True, choices=[('apartamento', 'Apartamento'), ('enfermaria', 'Enfermaria')], max_length=100, null=True, verbose_name='Acomodação'),
        ),
    ]
