# Generated by Django 5.0.7 on 2025-12-23 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0075_alter_procedimento_acomodacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_fim',
            field=models.TimeField(default=datetime.datetime(2025, 12, 23, 17, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Fim do Turno'),
        ),
        migrations.AlterField(
            model_name='escalaanestesiologista',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 12, 23, 8, 0, tzinfo=datetime.timezone.utc), verbose_name='Hora de Início do Turno'),
        ),
    ]
