# Generated by Django 5.0.7 on 2024-11-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0040_alter_escalaanestesiologista_hora_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoFinancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobranca', models.CharField(blank=True, choices=[('cooperativa', 'Cooperativa'), ('hospital', 'Hospital'), ('particular', 'Direta')], max_length=20, null=True, verbose_name='Cobrança via')),
                ('valor_cobranca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('tipo_pagamento_direto', models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Tipo de pagamento direto')),
                ('procedimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financas', to='agenda.procedimento')),
            ],
            options={
                'verbose_name': 'Financeiro do Procedimento',
                'verbose_name_plural': 'Financeiro dos Procedimentos',
            },
        ),
    ]
