# Generated by Django 5.0.7 on 2024-12-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_transfer_finance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentofinancas',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='status_pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Em Andamento'), ('glosa', 'Glosa')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
