# Generated by Django 5.0.7 on 2024-12-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0044_alter_escalaanestesiologista_hora_fim_and_more'),
        ('financas', '0003_procedimentofinancas_data_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a_vencer', 'A Vencer'), ('pago', 'Pago'), ('atrasado', 'Pagamento Atrasado')], default='a_vencer', max_length=20, verbose_name='Status')),
                ('procedimento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesa', to='agenda.procedimento')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
