# Generated by Django 5.0.7 on 2025-01-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_despesas'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentofinancas',
            name='cpsa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CPSA'),
        ),
    ]
