# Generated by Django 5.0.7 on 2025-01-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_procedimentofinancas_cpsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='status',
        ),
        migrations.AddField(
            model_name='despesas',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
