# Generated by Django 5.0.7 on 2025-01-10 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_remove_despesas_status_despesas_pago'),
        ('registration', '0007_customuser_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.groups', verbose_name='Grupo'),
        ),
    ]
