# Generated by Django 5.0.7 on 2025-03-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_despesas_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpsa_id', models.CharField(max_length=255)),
                ('conciliado', models.BooleanField(null=True)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('procedimento_financas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.procedimentofinancas')),
            ],
            options={
                'unique_together': {('procedimento_financas', 'cpsa_id')},
            },
        ),
    ]
