# Generated by Django 5.0.7 on 2025-04-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_conciliacaotentativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentofinancas',
            name='valor_cobranca',
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='valor_a_recuperar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor A Recuperar'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='valor_faturado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Faturado'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='valor_recuperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Recuperado (Glosa)'),
        ),
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='cpsa',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='CPSA'),
        ),
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='status_pagamento',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Em Andamento'), ('glosa', 'Glosa'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
