# Generated by Django 5.0.7 on 2025-04-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_remove_procedimentofinancas_valor_cobranca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimentofinancas',
            old_name='valor_a_recuperar',
            new_name='valor_acatado',
        ),
    ]
