# Generated by Django 5.0.7 on 2025-04-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_rename_valor_a_recuperar_procedimentofinancas_valor_acatado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='status_pagamento',
            field=models.CharField(choices=[('em_processamento', 'Em Processamento'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('recurso_de_glosa', 'Recurso de Glosa'), ('processo_finalizado', 'Processo Finalizado'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
