# Generated by Django 5.0.7 on 2025-04-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0056_alter_escalaanestesiologista_hora_fim_and_more'),
        ('financas', '0011_alter_procedimentofinancas_status_pagamento'),
        ('registration', '0014_customuser_privacy_policy_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentofinancas',
            name='api_cooperado_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cooperado (API)'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='api_data_cirurgia',
            field=models.DateField(blank=True, null=True, verbose_name='Data Cirurgia (API)'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='api_hospital_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hospital (API)'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='api_paciente_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Paciente (API)'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.groups', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='procedimento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financas', to='agenda.procedimento'),
        ),
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='status_pagamento',
            field=models.CharField(choices=[('em_processamento', 'Em Processamento'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('recurso_de_glosa', 'Recurso de Glosa'), ('processo_finalizado', 'Processo Finalizado'), ('cancelada', 'Cancelada')], default='em_processamento', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
