# Generated by Django 5.0.7 on 2025-05-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0060_alter_escalaanestesiologista_hora_fim_and_more'),
        ('financas', '0012_procedimentofinancas_api_cooperado_nome_and_more'),
        ('registration', '0016_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financas_records', to='agenda.procedimento'),
        ),
        migrations.AddConstraint(
            model_name='procedimentofinancas',
            constraint=models.UniqueConstraint(condition=models.Q(('cpsa__isnull', False), ('procedimento__isnull', False)), fields=('procedimento', 'cpsa'), name='unique_cpsa_per_procedure'),
        ),
    ]
