# Generated by Django 5.0.7 on 2025-09-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0014_despesasrecorrentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='tipo_pagamento_direto',
            field=models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('boleto', 'Boleto'), ('via_cirurgiao', 'Via Cirurgião'), ('cortesia', 'Cortesia')], max_length=20, null=True, verbose_name='Tipo de pagamento direto'),
        ),
    ]
