# Generated by Django 5.0.7 on 2025-09-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0015_alter_procedimentofinancas_tipo_pagamento_direto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='tipo_cobranca',
            field=models.CharField(blank=True, choices=[('cooperativa', 'Cooperativa'), ('hospital', 'Hospital'), ('particular', 'Direta'), ('via_cirurgiao', 'Via Cirurgião'), ('cortesia', 'Cortesia')], max_length=20, null=True, verbose_name='Cobrança via'),
        ),
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='tipo_pagamento_direto',
            field=models.CharField(blank=True, choices=[('cartao', 'Cartão'), ('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('boleto', 'Boleto')], max_length=20, null=True, verbose_name='Tipo de pagamento direto'),
        ),
    ]
