# Generated by Django 5.0.7 on 2025-10-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0016_alter_procedimentofinancas_tipo_cobranca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentofinancas',
            name='matricula',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='procedimentofinancas',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha'),
        ),
    ]
