# Generated by Django 5.0.7 on 2025-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0017_procedimentofinancas_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentofinancas',
            name='plantao_eletiva',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Plantão/Eletiva (API)'),
        ),
    ]
