# Generated by Django 5.0.7 on 2025-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0018_procedimentofinancas_plantao_eletiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimentofinancas',
            name='tipo_cobranca',
            field=models.CharField(blank=True, choices=[('cooperativa', 'Cooperativa'), ('hospital', 'Hospital'), ('coi', 'COI'), ('amil', 'Amil'), ('particular', 'Direta'), ('via_cirurgiao', 'Via Cirurgião'), ('cortesia', 'Cortesia')], max_length=20, null=True, verbose_name='Cobrança via'),
        ),
    ]
