# Generated by Django 5.0.7 on 2026-01-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0019_alter_procedimentofinancas_tipo_cobranca'),
        ('registration', '0017_remove_customuser_user_type_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em Execução'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_guias', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('linked_count', models.IntegerField(default=0)),
                ('current_step', models.CharField(default='Iniciando...', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacao_jobs', to='registration.groups')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
