# Generated by Django 5.0.7 on 2024-08-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('secretaria', 'Secretária'), ('gestor', 'Gestor'), ('anestesista', 'Anestesista')], default='anestesista', max_length=40, verbose_name='Tipo de usuário'),
        ),
    ]
