# Generated by Django 5.0.7 on 2024-08-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='No address provided', max_length=255)),
                ('surgery_center_phone', models.CharField(default='0000000000', max_length=15)),
                ('hospital_phone', models.CharField(default='0000000000', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('specialty', models.CharField(default='Cirurgião Geral', max_length=255)),
                ('estado', models.CharField(default='RJ', max_length=2, unique=True)),
                ('crm', models.CharField(default='', max_length=20, unique=True)),
                ('rqe', models.CharField(default='', max_length=20, unique=True)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('notes', models.TextField(blank=True, default='No notes')),
            ],
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='medical_license',
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='specialization',
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='admission_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='crm',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='date_of_birth',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='estado',
            field=models.CharField(default='RJ', max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='function',
            field=models.CharField(default='Anestesista', max_length=255),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='phone',
            field=models.CharField(default='5521999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='responsible_hours',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='role_in_group',
            field=models.CharField(default='Membro', max_length=255),
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='rqe',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
