# Generated by Django 5.0.7 on 2024-08-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_groups_alter_anesthesiologist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anesthesiologist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.groups', verbose_name='Grupo'),
        ),
    ]
