# Generated by Django 5.0.7 on 2024-08-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='anesthesiologist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.customuser'),
        ),
    ]
