# Generated by Django 5.0.7 on 2024-09-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_anesthesiologist_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail do Grupo'),
        ),
    ]
