# Generated by Django 5.0.7 on 2024-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_anesthesiologist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anesthesiologist',
            name='rqe',
        ),
        migrations.RemoveField(
            model_name='surgeon',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='surgeon',
            name='rqe',
        ),
        migrations.AddField(
            model_name='anesthesiologist',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='estado',
            field=models.CharField(default='RJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='role_in_group',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('rotina', 'Rotina'), ('plantonista', 'Plantonista'), ('coringa', 'Coringa')], default='rotina', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='address',
            field=models.CharField(default='Sem endereço fornecido', max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='hospital_phone',
            field=models.CharField(default='5521999999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='surgery_center_phone',
            field=models.CharField(default='5521999999999', max_length=15),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='notes',
            field=models.TextField(blank=True, default='Sem notas'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='phone',
            field=models.CharField(default='5521999999999', max_length=15),
        ),
    ]
