# Generated by Django 5.0.7 on 2024-08-13 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_anesthesiologist_rqe_remove_surgeon_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anesthesiologist',
            name='admission_date',
            field=models.DateField(default='1970-01-01', verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=15, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='crm',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='date_of_birth',
            field=models.DateField(default='1970-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='estado',
            field=models.CharField(default='RJ', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='function',
            field=models.CharField(default='Anestesista', max_length=255, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='phone',
            field=models.CharField(default='5521999999999', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='responsible_hours',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Horário Responsável'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='role_in_group',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('rotina', 'Rotina'), ('plantonista', 'Plantonista'), ('coringa', 'Coringa')], default='rotina', max_length=255, verbose_name='Cargo no grupo'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.customuser', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('secretaria', 'Secretária'), ('gestor', 'Gestor'), ('anestesista', 'Anestesista'), ('admin', 'Administrador do Sistema')], default='anestesista', max_length=40, verbose_name='Tipo de usuário'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='address',
            field=models.CharField(default='No address provided', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='hospital_phone',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Telefone do Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='surgery_center_phone',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Telefone do Centro Cirúrgico'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='crm',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='notes',
            field=models.TextField(blank=True, default='No notes', verbose_name='Notas (Sugestões de anestesia)'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='specialty',
            field=models.CharField(default='Cirurgião Geral', max_length=255, verbose_name='Especialidade'),
        ),
    ]
