# Generated by Django 5.0.7 on 2024-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_groups_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalclinic',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='hospital_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do Hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='surgery_center_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do Centro Cirúrgico'),
        ),
    ]
