# Generated by Django 5.0.7 on 2025-02-25 20:16

from django.db import migrations

def forwards_func(apps, schema_editor):
    CustomUser = apps.get_model('registration', 'CustomUser')
    Membership = apps.get_model('registration', 'Membership')
    # We'll only create memberships for users who currently have a non-null group
    users_with_groups = CustomUser.objects.exclude(group__isnull=True)
    
    for user in users_with_groups:
        # Create or get a Membership row so we don't duplicate if it already exists
        # We'll copy the user's existing "validado" value into Membership
        Membership.objects.get_or_create(
            user=user,
            group=user.group,
            defaults={'validado': user.validado}
        )

def backwards_func(apps, schema_editor):
    """
    In a typical one-way migration, you can either leave this empty or
    delete membership rows if you want. We'll keep it empty since
    "reversing" might not be needed in production.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_membership'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
