# Generated by Django 5.0.7 on 2025-03-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_populate_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='connection_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Connection Key'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Externo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador Global'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_token_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação de Token'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='origem',
            field=models.CharField(blank=True, choices=[('PF', 'Médico'), ('PJ', 'Administrativo')], max_length=2, null=True, verbose_name='Origem no Sistema'),
        ),
        migrations.AddField(
            model_name='groups',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
