# Generated by Django 5.0.7 on 2025-03-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_customuser_connection_key_customuser_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('gestor', 'Administração'), ('anestesista', 'Anestesista')], default='anestesista', max_length=40, verbose_name='Tipo de usuário'),
        ),
    ]
