# Generated by Django 5.0.7 on 2025-03-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anesthesiologist',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='crm',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='estado',
            field=models.CharField(blank=True, default='RJ', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='anesthesiologist',
            name='responsible_hours',
            field=models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Horário Responsável'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='crm',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CRM'),
        ),
        migrations.AlterField(
            model_name='surgeon',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefone'),
        ),
    ]
