# Generated by Django 5.0.7 on 2025-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_alter_anesthesiologist_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gestor_anesthesiologist_check_complete',
            field=models.BooleanField(default=False, verbose_name='Verificação de Anestesista para Gestor Completa'),
        ),
    ]
