# Generated by Django 5.0.7 on 2025-04-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_customuser_gestor_anesthesiologist_check_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='privacy_policy_agreed',
            field=models.BooleanField(default=False, verbose_name='Concordou com a Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='terms_agreed',
            field=models.BooleanField(default=False, verbose_name='Concordou com os Termos de Serviço'),
        ),
    ]
