# Generated by Django 5.0.7 on 2025-05-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_customuser_privacy_policy_agreed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gestor_anesthesiologist_check_complete',
        ),
    ]
