# Generated by Django 5.0.7 on 2025-06-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_customuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('gestor', 'Administração'), ('anestesista', 'Anestesista')], default='anestesista', max_length=40, verbose_name='Cargo no Grupo'),
        ),
    ]
