# Generated by Django 5.0.7 on 2024-10-22 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0025_procedimento_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoRPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_alta_rpa', models.TimeField(verbose_name='Tempo até atingir alta RPA*')),
                ('dor_pos_operatoria', models.BooleanField(verbose_name='Dor pós operatória imediata*')),
                ('escala', models.CharField(choices=[('EVA', 'EVA - Adultos e crianças maiores que 7 anos.'), ('FLACC', 'FLACC - Crianças menores que 7 anos ou pacientes não verbais.'), ('BPS', 'BPS - Pacientes intubados e sedados.'), ('PAINAD-B', 'PAINAD-B - Pacientes com demência avançada.')], max_length=10, verbose_name='Qual escala?*')),
                ('eva_score', models.IntegerField(blank=True, null=True, verbose_name='Quanto?')),
                ('face', models.IntegerField(blank=True, null=True, verbose_name='Face')),
                ('pernas', models.IntegerField(blank=True, null=True, verbose_name='Pernas')),
                ('atividade', models.IntegerField(blank=True, null=True, verbose_name='Atividade')),
                ('choro', models.IntegerField(blank=True, null=True, verbose_name='Choro')),
                ('consolabilidade', models.IntegerField(blank=True, null=True, verbose_name='Consolabilidade')),
                ('expressao_facial', models.IntegerField(blank=True, null=True, verbose_name='Expressão facial')),
                ('movimentos_membros_superiores', models.IntegerField(blank=True, null=True, verbose_name='Movimentos dos membros superiores')),
                ('adaptacao_ventilador', models.IntegerField(blank=True, null=True, verbose_name='Adaptação ao ventilador mecânico')),
                ('respiracao', models.IntegerField(blank=True, null=True, verbose_name='Respiração')),
                ('vocalizacao_negativa', models.IntegerField(blank=True, null=True, verbose_name='Vocalização negativa')),
                ('expressao_facial_painad', models.IntegerField(blank=True, null=True, verbose_name='Expressão facial')),
                ('linguagem_corporal', models.IntegerField(blank=True, null=True, verbose_name='Linguagem corporal')),
                ('consolabilidade_painad', models.IntegerField(blank=True, null=True, verbose_name='Consolabilidade')),
                ('evento_adverso', models.BooleanField(blank=True, null=True, verbose_name='Evento adverso evitável na RPA*')),
                ('evento_adverso_qual', models.TextField(blank=True, null=True, verbose_name='Qual?')),
                ('ponv', models.BooleanField(blank=True, null=True, verbose_name='PONV na RPA*')),
                ('procedimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_rpa', to='agenda.procedimento')),
            ],
            options={
                'verbose_name': 'Avaliação RPA',
                'verbose_name_plural': 'Avaliações RPA',
            },
        ),
    ]
