# Generated by Django 5.0.7 on 2024-10-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaorpa',
            name='dor_pos_operatoria',
            field=models.BooleanField(verbose_name='Dor pós operatória imediata'),
        ),
        migrations.AlterField(
            model_name='avaliacaorpa',
            name='escala',
            field=models.CharField(choices=[('EVA', '<b>EVA</b> Adultos e crianças maiores que 7 anos.'), ('FLACC', '<b>FLACC</b> Crianças menores que 7 anos ou pacientes não verbais.'), ('BPS', '<b>BPS</b> Pacientes intubados e sedados.'), ('PAINAD-B', '<b>PAINAD-B</b> Pacientes com demência avançada.')], max_length=10, verbose_name='Qual escala?'),
        ),
        migrations.AlterField(
            model_name='avaliacaorpa',
            name='evento_adverso',
            field=models.BooleanField(blank=True, null=True, verbose_name='Evento adverso evitável na RPA'),
        ),
        migrations.AlterField(
            model_name='avaliacaorpa',
            name='ponv',
            field=models.BooleanField(blank=True, null=True, verbose_name='PONV na RPA'),
        ),
        migrations.AlterField(
            model_name='avaliacaorpa',
            name='tempo_alta_rpa',
            field=models.TimeField(verbose_name='Tempo até atingir alta RPA'),
        ),
    ]
