# Generated by Django 5.0.7 on 2024-10-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_alter_avaliacaorpa_dor_pos_operatoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaorpa',
            name='escala',
            field=models.CharField(choices=[('EVA', '<span class="scale-name">EVA</span> &nbsp; &nbsp; &nbsp;Adultos e crianças maiores que 7 anos.'), ('FLACC', '<span class="scale-name">FLACC</span> &nbsp; &nbsp; &nbsp;Crianças menores que 7 anos ou pacientes não verbais.'), ('BPS', '<span class="scale-name">BPS</span> &nbsp; &nbsp; &nbsp;Pacientes intubados e sedados.'), ('PAINAD-B', '<span class="scale-name">PAINAD-B</span> &nbsp; &nbsp; &nbsp;Pacientes com demência avançada.')], max_length=10, verbose_name='Qual escala?'),
        ),
    ]
