# Generated by Django 5.0.7 on 2024-11-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0040_alter_escalaanestesiologista_hora_fim_and_more'),
        ('qualidade', '0003_alter_avaliacaorpa_escala'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario_inicio_efetivo', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Início Efetivo')),
                ('data_horario_fim_efetivo', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Término Efetivo')),
                ('eventos_adversos_graves', models.BooleanField(blank=True, null=True, verbose_name='Eventos adversos graves')),
                ('eventos_adversos_graves_desc', models.CharField(blank=True, choices=[('broncoaspiracao', 'Broncoaspiração'), ('pcr', 'Parada Cardiorrespiratória (PCR)'), ('hemorragia', 'Hemorragia Maciça'), ('embolia', 'Embolia Pulmonar'), ('choque_anafilatico', 'Choque Anafilático'), ('lesao_orgao', 'Lesão de Órgão Não-Alvo'), ('iam', 'Infarto Agudo do Miocárdio'), ('avc', 'Acidente Vascular Cerebral (AVC)'), ('sirs', 'Síndrome da Resposta Inflamatória Sistêmica (SIRS)'), ('tvp', 'Trombose Venosa Profunda (TVP)'), ('ira', 'Insuficiência Renal Aguda'), ('pneumotorax', 'Pneumotórax'), ('sind_compartimental', 'Síndrome Compartimental'), ('hipertermia', 'Hipertermia Maligna'), ('deiscencia', 'Deiscência de Sutura'), ('lesao_nervo', 'Lesão de Nervo Periférico'), ('cegueira', 'Cegueira Pós-Operatória'), ('sdra', 'Síndrome do Desconforto Respiratório Agudo (SDRA)'), ('reacao_transfusional', 'Reação Transfusional Hemolítica Aguda'), ('sepse', 'Sepse Pós-Operatória')], max_length=50, null=True, verbose_name='Descrição do evento adverso grave')),
                ('reacao_alergica_grave', models.BooleanField(blank=True, null=True, verbose_name='Reação alérgica grave')),
                ('reacao_alergica_grave_desc', models.TextField(blank=True, null=True, verbose_name='Descrição da reação alérgica grave')),
                ('encaminhamento_uti', models.BooleanField(blank=True, null=True, verbose_name='Encaminhamentos não programado à UTI')),
                ('evento_adverso_evitavel', models.BooleanField(blank=True, null=True, verbose_name='Evento adverso evitável')),
                ('adesao_checklist', models.BooleanField(blank=True, null=True, verbose_name='Adesão ao check list de segurança')),
                ('uso_tecnicas_assepticas', models.BooleanField(blank=True, null=True, verbose_name='Uso adequado de técnicas assépticas')),
                ('conformidade_diretrizes', models.BooleanField(blank=True, null=True, verbose_name='Conformidade com diretrizes e protocolos')),
                ('ponv', models.BooleanField(blank=True, null=True, verbose_name='PONV')),
                ('adesao_profilaxia', models.BooleanField(blank=True, null=True, verbose_name='Adesão aos protocolos de profilaxia antibiótica e de prevenção de TVP/TEP')),
                ('satisfacao_geral', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Satisfação geral')),
                ('clareza_informacoes', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Clareza das informações')),
                ('comunicacao_disponibilidade', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Comunicação e disponibilidade')),
                ('conforto_seguranca', models.IntegerField(blank=True, choices=[(1, 'Muito Insatisfeito'), (2, 'Insatisfeito'), (3, 'Neutro'), (4, 'Satisfeito'), (5, 'Muito Satisfeito')], null=True, verbose_name='Conforto e segurança')),
                ('comentario_adicional', models.TextField(blank=True, null=True, verbose_name='Comentário adicional')),
                ('csat_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CSAT Score')),
                ('dor_pos_operatoria', models.BooleanField(blank=True, null=True, verbose_name='Dor pós operatória imediata')),
                ('escala', models.CharField(blank=True, choices=[('EVA', '<span class="scale-name">EVA</span> &nbsp; &nbsp; &nbsp;Adultos e crianças maiores que 7 anos.'), ('FLACC', '<span class="scale-name">FLACC</span> &nbsp; &nbsp; &nbsp;Crianças menores que 7 anos ou pacientes não verbais.'), ('BPS', '<span class="scale-name">BPS</span> &nbsp; &nbsp; &nbsp;Pacientes intubados e sedados.'), ('PAINAD-B', '<span class="scale-name">PAINAD-B</span> &nbsp; &nbsp; &nbsp;Pacientes com demência avançada.')], max_length=10, null=True, verbose_name='Qual escala?')),
                ('eva_score', models.IntegerField(blank=True, null=True, verbose_name='Quanto?')),
                ('face', models.IntegerField(blank=True, null=True, verbose_name='Face')),
                ('pernas', models.IntegerField(blank=True, null=True, verbose_name='Pernas')),
                ('atividade', models.IntegerField(blank=True, null=True, verbose_name='Atividade')),
                ('choro', models.IntegerField(blank=True, null=True, verbose_name='Choro')),
                ('consolabilidade', models.IntegerField(blank=True, null=True, verbose_name='Consolabilidade')),
                ('expressao_facial', models.IntegerField(blank=True, null=True, verbose_name='Expressão facial')),
                ('movimentos_membros_superiores', models.IntegerField(blank=True, null=True, verbose_name='Movimentos dos membros superiores')),
                ('adaptacao_ventilador', models.IntegerField(blank=True, null=True, verbose_name='Adaptação ao ventilador mecânico')),
                ('respiracao', models.IntegerField(blank=True, null=True, verbose_name='Respiração')),
                ('vocalizacao_negativa', models.IntegerField(blank=True, null=True, verbose_name='Vocalização negativa')),
                ('expressao_facial_painad', models.IntegerField(blank=True, null=True, verbose_name='Expressão facial')),
                ('linguagem_corporal', models.IntegerField(blank=True, null=True, verbose_name='Linguagem corporal')),
                ('consolabilidade_painad', models.IntegerField(blank=True, null=True, verbose_name='Consolabilidade')),
                ('procedimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualidade', to='agenda.procedimento')),
            ],
            options={
                'verbose_name': 'Qualidade do Procedimento',
                'verbose_name_plural': 'Qualidade dos Procedimentos',
            },
        ),
    ]
