# Generated by Django 5.0.7 on 2025-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0005_transfer_quality_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentoqualidade',
            name='adesao_profilaxia',
        ),
        migrations.AddField(
            model_name='procedimentoqualidade',
            name='adesao_prevencao_tvp_tep',
            field=models.BooleanField(blank=True, null=True, verbose_name='Adesão aos protocolos de prevenção de TVP/TEP'),
        ),
        migrations.AddField(
            model_name='procedimentoqualidade',
            name='adesao_profilaxia_antibiotica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Adesão aos protocolos de profilaxia antibiótica'),
        ),
    ]
