# Generated by Django 5.0.7 on 2025-06-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0006_remove_procedimentoqualidade_adesao_profilaxia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentoqualidade',
            name='evento_adverso_evitavel_desc',
            field=models.CharField(blank=True, choices=[('dano_dentario', 'Dano dentário'), ('erro_medicacao', 'Erro de medicação'), ('erro_posologia', 'Erro de posologia'), ('erro_via_administracao', 'Erro de via de administração'), ('falha_equipamento', 'Falha de equipamento'), ('hipertermia_maligna_crise', 'Hipertermia maligna (crise)'), ('hipotermia_nao_intencional', 'Hipotermia não intencional'), ('hipoxia_hipoventilacao_evitavel', 'Hipóxia/Hipoventilação'), ('injecao_intratecal_inadvertida', 'Injeção intratecal inadvertida de medicações não aprovadas'), ('lesao_nervosa_perioperatoria', 'Lesão nervosa perioperatória'), ('lesoes_oculares', 'Lesões oculares'), ('nvpo_nao_prevenido', 'Náuseas e vômitos pós-operatórios (NVPO) não prevenidos'), ('perda_sangue_nao_controlada', 'Perda de sangue não controlada'), ('perfuracao_inadvertida_orgaos', 'Perfuração inadvertida de órgãos'), ('queimaduras', 'Queimaduras'), ('reacao_anafilatica_alergica', 'Reação anafilática/alérgica'), ('via_aerea_dificil_nao_manejada', 'Via aérea difícil não antecipada/não manejada')], max_length=50, null=True, verbose_name='Qual?'),
        ),
        migrations.AlterField(
            model_name='procedimentoqualidade',
            name='eventos_adversos_graves_desc',
            field=models.CharField(blank=True, choices=[('avc', 'Acidente Vascular Cerebral (AVC)'), ('broncoaspiracao', 'Broncoaspiração'), ('choque_anafilatico', 'Choque Anafilático'), ('embolia_pulmonar', 'Embolia Pulmonar'), ('hemorragia_macica', 'Hemorragia Maciça'), ('hipertensao_grave', 'Hipertensão grave necessitando medicação'), ('hipertermia_maligna', 'Hipertermia Maligna'), ('hipotensao_amina', 'Hipotensão necessitando amina'), ('hipoxia_hipoventilacao', 'Hipóxia/Hipoventilação'), ('iam', 'Infarto Agudo do Miocárdio'), ('lesao_nervo_periferico', 'Lesão de Nervo Periférico'), ('lesao_orgao_nao_alvo', 'Lesão de Órgão Não-Alvo'), ('pcr', 'Parada Cardiorrespiratória (PCR)'), ('pneumotorax', 'Pneumotórax'), ('reacao_transfusional', 'Reação Transfusional'), ('tvp', 'Trombose Venosa Profunda (TVP)'), ('tromboembolismo_pulmonar', 'Tromboembolismo pulmonar'), ('via_aerea_dificil', 'Via aérea difícil')], max_length=50, null=True, verbose_name='Descrição do evento adverso grave'),
        ),
    ]
