# Generated by Django 5.0.7 on 2025-06-28 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "qualidade",
            "0007_procedimentoqualidade_evento_adverso_evitavel_desc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="procedimentoqualidade",
            name="abreviacao_jejum",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Houve abreviação de jejum?"
            ),
        ),
        migrations.AddField(
            model_name="procedimentoqualidade",
            name="escala_aldrete",
            field=models.IntegerField(
                blank=True,
                help_text="Valor de 0 a 10",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Escala de Aldrete",
            ),
        ),
    ]
